import { Globe, Gamepad2, Laugh, TrendingUp, Shirt, Music, Sparkles, FlaskConical, Film, Tv, Flag, Stethoscope, Youtube, PawPrint, type LucideIcon } from "lucide-react";

export type CategoryId = 
  | "world_news"
  | "gaming"
  | "memes"
  | "trends"
  | "fashion"
  | "music"
  | "interesting"
  | "facts_research"
  | "movies"
  | "series"
  | "russia_news"
  | "medicine"
  | "youtube_trends"
  | "pets";

export interface RSSSource {
  name: string;
  url: string;
}

export interface CategoryPreset {
  id: CategoryId;
  icon: LucideIcon;
  ruOnly?: boolean;
  sources: {
    en: RSSSource[];
    ru: RSSSource[];
  };
}

export const categoryPresets: CategoryPreset[] = [
  {
    id: "world_news",
    icon: Globe,
    sources: {
      en: [
        { name: "BBC News", url: "https://feeds.bbci.co.uk/news/world/rss.xml" },
        { name: "Reuters World", url: "https://feeds.reuters.com/Reuters/worldNews" },
        { name: "Associated Press", url: "https://feeds.apnews.com/rss/apf-worldnews" },
        { name: "The Guardian", url: "https://www.theguardian.com/world/rss" },
        { name: "Al Jazeera", url: "https://www.aljazeera.com/xml/rss/all.xml" },
        { name: "CNN International", url: "https://rss.cnn.com/rss/edition_world.rss" },
        { name: "NPR World", url: "https://feeds.npr.org/1004/rss.xml" },
        { name: "ABC News", url: "https://abcnews.go.com/abcnews/internationalheadlines" },
        { name: "CBS News", url: "https://www.cbsnews.com/latest/rss/world" },
        { name: "France 24", url: "https://www.france24.com/en/rss" },
        { name: "DW News", url: "https://rss.dw.com/xml/rss-en-all" },
        { name: "Euronews", url: "https://www.euronews.com/rss?level=theme&name=news" },
        { name: "The Independent", url: "https://www.independent.co.uk/news/world/rss" },
        { name: "Sky News", url: "https://feeds.skynews.com/feeds/rss/world.xml" },
        { name: "TIME World", url: "https://time.com/feed/" },
        { name: "Newsweek", url: "https://www.newsweek.com/rss" },
        { name: "The Hill", url: "https://thehill.com/feed/" },
        { name: "Politico", url: "https://www.politico.com/rss/politicopicks.xml" },
        { name: "Washington Post", url: "https://feeds.washingtonpost.com/rss/world" },
        { name: "NY Times World", url: "https://rss.nytimes.com/services/xml/rss/nyt/World.xml" },
      ],
      ru: [
        { name: "ТАСС", url: "https://tass.ru/rss/v2.xml" },
        { name: "Интерфакс", url: "https://www.interfax.ru/rss.asp" },
        { name: "РБК", url: "https://rssexport.rbc.ru/rbcnews/news/30/full.rss" },
        { name: "BBC Russian", url: "https://feeds.bbci.co.uk/russian/rss.xml" },
        { name: "Meduza", url: "https://meduza.io/rss/all" },
        { name: "РИА Новости", url: "https://ria.ru/export/rss2/archive/index.xml" },
        { name: "Лента.ру", url: "https://lenta.ru/rss" },
        { name: "Газета.ру", url: "https://www.gazeta.ru/export/rss/lenta.xml" },
        { name: "Новая газета", url: "https://novayagazeta.ru/rss/all.xml" },
        { name: "Коммерсант", url: "https://www.kommersant.ru/RSS/news.xml" },
        { name: "Ведомости", url: "https://www.vedomosti.ru/rss/news" },
        { name: "Известия", url: "https://iz.ru/xml/rss/all.xml" },
        { name: "RT на русском", url: "https://russian.rt.com/rss" },
        { name: "Sputnik", url: "https://sputniknews.com/export/rss2/archive/index.xml" },
        { name: "Новости Mail.ru", url: "https://news.mail.ru/rss/" },
        { name: "НТВ", url: "https://www.ntv.ru/rss/" },
        { name: "Первый канал", url: "https://www.1tv.ru/rss" },
        { name: "Российская газета", url: "https://rg.ru/xml/index.xml" },
        { name: "Fontanka", url: "https://www.fontanka.ru/fontanka.rss" },
        { name: "МК", url: "https://www.mk.ru/rss/index.xml" },
      ],
    },
  },
  {
    id: "gaming",
    icon: Gamepad2,
    sources: {
      en: [
        { name: "IGN", url: "https://feeds.feedburner.com/ign/games-all" },
        { name: "GameSpot", url: "https://www.gamespot.com/feeds/news/" },
        { name: "PC Gamer", url: "https://www.pcgamer.com/rss/" },
        { name: "Kotaku", url: "https://kotaku.com/rss" },
        { name: "VGC", url: "https://www.videogameschronicle.com/feed/" },
        { name: "Polygon", url: "https://www.polygon.com/rss/index.xml" },
        { name: "Eurogamer", url: "https://www.eurogamer.net/?format=rss" },
        { name: "Rock Paper Shotgun", url: "https://www.rockpapershotgun.com/feed" },
        { name: "Destructoid", url: "https://www.destructoid.com/feed/" },
        { name: "GamesRadar", url: "https://www.gamesradar.com/rss/" },
        { name: "Nintendo Life", url: "https://www.nintendolife.com/feeds/latest" },
        { name: "Push Square", url: "https://www.pushsquare.com/feeds/latest" },
        { name: "Pure Xbox", url: "https://www.purexbox.com/feeds/latest" },
        { name: "The Verge Gaming", url: "https://www.theverge.com/games/rss/index.xml" },
        { name: "Wired Gaming", url: "https://www.wired.com/feed/category/games/latest/rss" },
        { name: "Gamasutra", url: "https://www.gamedeveloper.com/rss.xml" },
        { name: "PCGamesN", url: "https://www.pcgamesn.com/feed" },
        { name: "r/Games", url: "https://www.reddit.com/r/Games/.rss" },
        { name: "r/PCGaming", url: "https://www.reddit.com/r/pcgaming/.rss" },
        { name: "r/Nintendo", url: "https://www.reddit.com/r/nintendo/.rss" },
      ],
      ru: [
        { name: "Игромания", url: "https://www.igromania.ru/rss/news.xml" },
        { name: "StopGame", url: "https://stopgame.ru/rss/news.xml" },
        { name: "DTF", url: "https://dtf.ru/rss" },
        { name: "Канобу", url: "https://kanobu.ru/rss/all.xml" },
        { name: "PlayGround", url: "https://www.playground.ru/rss/news.xml" },
        { name: "GoHa.ru", url: "https://www.goha.ru/rss" },
        { name: "GameMAG", url: "https://gamemag.ru/rss" },
        { name: "3DNews Games", url: "https://3dnews.ru/games/rss/" },
        { name: "Shazoo", url: "https://shazoo.ru/feed" },
        { name: "Riot Pixels", url: "https://riotpixels.com/feed/" },
        { name: "Overclockers Games", url: "https://overclockers.ru/games/rss" },
        { name: "Cybersport.ru", url: "https://www.cybersport.ru/rss" },
        { name: "Virtus.pro", url: "https://virtus.pro/ru/rss" },
        { name: "Games Mail.ru", url: "https://games.mail.ru/rss/" },
        { name: "Навигатор", url: "https://navigatoria.net/feed/" },
        { name: "ProGamer", url: "https://progamer.ru/feed/" },
        { name: "GameGuru", url: "https://gameguru.ru/feed/" },
        { name: "App2Top", url: "https://app2top.ru/feed/" },
        { name: "r/Pikabu Games", url: "https://www.reddit.com/r/Pikabu/.rss?feed=games" },
        { name: "VK Gaming", url: "https://vk.com/rss.php?list=games" },
      ],
    },
  },
  {
    id: "memes",
    icon: Laugh,
    sources: {
      en: [
        { name: "Know Your Meme", url: "https://knowyourmeme.com/feed" },
        { name: "r/memes", url: "https://www.reddit.com/r/memes/.rss" },
        { name: "r/dankmemes", url: "https://www.reddit.com/r/dankmemes/.rss" },
        { name: "r/me_irl", url: "https://www.reddit.com/r/me_irl/.rss" },
        { name: "r/funny", url: "https://www.reddit.com/r/funny/.rss" },
        { name: "r/MemeEconomy", url: "https://www.reddit.com/r/MemeEconomy/.rss" },
        { name: "r/AdviceAnimals", url: "https://www.reddit.com/r/AdviceAnimals/.rss" },
        { name: "r/wholesomememes", url: "https://www.reddit.com/r/wholesomememes/.rss" },
        { name: "r/PrequelMemes", url: "https://www.reddit.com/r/PrequelMemes/.rss" },
        { name: "r/ProgrammerHumor", url: "https://www.reddit.com/r/ProgrammerHumor/.rss" },
        { name: "r/surrealmemes", url: "https://www.reddit.com/r/surrealmemes/.rss" },
        { name: "r/ComedyCemetery", url: "https://www.reddit.com/r/ComedyCemetery/.rss" },
        { name: "9GAG", url: "https://9gag.com/v1/feed" },
        { name: "Cheezburger", url: "https://cheezburger.com/feed" },
        { name: "eBaum's World", url: "https://www.ebaumsworld.com/rss/feed" },
        { name: "The Chive", url: "https://thechive.com/feed/" },
        { name: "CollegeHumor", url: "https://www.collegehumor.com/rss" },
        { name: "Dorkly", url: "https://www.dorkly.com/rss" },
        { name: "Memedroid", url: "https://www.memedroid.com/rss/popular" },
        { name: "Imgur Viral", url: "https://imgur.com/rss/viral" },
      ],
      ru: [
        { name: "Pikabu", url: "https://pikabu.ru/rss" },
        { name: "AdMe", url: "https://www.adme.ru/rss/" },
        { name: "Fishki", url: "https://fishki.net/rss" },
        { name: "JoyReactor", url: "https://joyreactor.cc/rss" },
        { name: "ЯПлакал", url: "https://www.yaplakal.com/rss.xml" },
        { name: "Leprosorium", url: "https://leprosorium.ru/rss" },
        { name: "Юмор FM", url: "https://www.yumorfm.ru/rss" },
        { name: "Bash.im", url: "https://bash.im/rss/" },
        { name: "Zadolba.li", url: "https://zadolba.li/rss" },
        { name: "IT Humor", url: "https://ithappens.me/rss" },
        { name: "r/ru_memes", url: "https://www.reddit.com/r/ru/.rss" },
        { name: "Развлекательный портал", url: "https://tjournal.ru/rss/humor" },
        { name: "Лепра Юмор", url: "https://leprosorium.ru/rss/humor" },
        { name: "Фишки Юмор", url: "https://fishki.net/humor/rss" },
        { name: "Пикабу Горячее", url: "https://pikabu.ru/rss/hot" },
        { name: "Пикабу Лучшее", url: "https://pikabu.ru/rss/best" },
        { name: "Memepedia RU", url: "https://memepedia.ru/feed/" },
        { name: "Мемы VK", url: "https://vk.com/rss.php?list=memes" },
        { name: "Смешные картинки", url: "https://www.anekdot.ru/rss/export.xml" },
        { name: "Anekdot.ru", url: "https://www.anekdot.ru/rss/export20.xml" },
      ],
    },
  },
  {
    id: "trends",
    icon: TrendingUp,
    sources: {
      en: [
        { name: "Google Trends US", url: "https://trends.google.com/trends/trendingsearches/daily/rss?geo=US" },
        { name: "Google Trends UK", url: "https://trends.google.com/trends/trendingsearches/daily/rss?geo=GB" },
        { name: "r/popular", url: "https://www.reddit.com/r/popular/.rss" },
        { name: "r/all", url: "https://www.reddit.com/r/all/.rss" },
        { name: "r/trending", url: "https://www.reddit.com/r/trendingsubreddits/.rss" },
        { name: "Hacker News", url: "https://news.ycombinator.com/rss" },
        { name: "Product Hunt", url: "https://www.producthunt.com/feed" },
        { name: "TechCrunch", url: "https://techcrunch.com/feed/" },
        { name: "The Verge", url: "https://www.theverge.com/rss/index.xml" },
        { name: "Mashable", url: "https://mashable.com/feeds/rss/all" },
        { name: "Buzzfeed Trending", url: "https://www.buzzfeed.com/index.xml" },
        { name: "Viral Viral Videos", url: "https://www.viralviralvideos.com/feed/" },
        { name: "Digg", url: "https://digg.com/rss/index.xml" },
        { name: "Slashdot", url: "https://rss.slashdot.org/Slashdot/slashdotMain" },
        { name: "Fark", url: "https://www.fark.com/fark.rss" },
        { name: "Boing Boing", url: "https://boingboing.net/feed" },
        { name: "Kottke", url: "https://kottke.org/index.xml" },
        { name: "Longform", url: "https://longform.org/feed.rss" },
        { name: "Pocket Hits", url: "https://getpocket.com/explore/feed" },
        { name: "Feedly Trending", url: "https://feedly.com/v3/feeds/trending" },
      ],
      ru: [
        { name: "Google Trends RU", url: "https://trends.google.com/trends/trendingsearches/daily/rss?geo=RU" },
        { name: "Яндекс.Новости", url: "https://news.yandex.ru/index.rss" },
        { name: "VC.ru", url: "https://vc.ru/rss" },
        { name: "Хабр Популярное", url: "https://habr.com/ru/rss/best/" },
        { name: "DTF Популярное", url: "https://dtf.ru/rss/popular" },
        { name: "TJ Популярное", url: "https://tjournal.ru/rss" },
        { name: "Пикабу Горячее", url: "https://pikabu.ru/rss/hot" },
        { name: "Lenta Главное", url: "https://lenta.ru/rss/top7" },
        { name: "RBC Главное", url: "https://rssexport.rbc.ru/rbcnews/news/20/full.rss" },
        { name: "Медуза Главное", url: "https://meduza.io/rss/top" },
        { name: "Sports.ru", url: "https://www.sports.ru/rss/main.xml" },
        { name: "Афиша Daily", url: "https://daily.afisha.ru/rss/" },
        { name: "The Village", url: "https://www.the-village.ru/feeds/rss" },
        { name: "Esquire Russia", url: "https://esquire.ru/rss" },
        { name: "GQ Russia", url: "https://www.gq.ru/rss" },
        { name: "Forbes Russia", url: "https://www.forbes.ru/newrss.xml" },
        { name: "РБК Тренды", url: "https://trends.rbc.ru/rss" },
        { name: "Секрет фирмы", url: "https://secretmag.ru/rss" },
        { name: "Inc Russia", url: "https://incrussia.ru/feed/" },
        { name: "LifeHacker RU", url: "https://lifehacker.ru/feed/" },
      ],
    },
  },
  {
    id: "fashion",
    icon: Shirt,
    sources: {
      en: [
        { name: "Vogue", url: "https://www.vogue.com/rss" },
        { name: "Business of Fashion", url: "https://www.businessoffashion.com/rss" },
        { name: "GQ Style", url: "https://www.gq.com/feed/rss" },
        { name: "Harper's Bazaar", url: "https://www.harpersbazaar.com/rss/all.xml/" },
        { name: "Elle", url: "https://www.elle.com/rss/all.xml/" },
        { name: "Cosmopolitan", url: "https://www.cosmopolitan.com/rss/all.xml/" },
        { name: "WWD", url: "https://wwd.com/feed/" },
        { name: "Fashionista", url: "https://fashionista.com/.rss/full/" },
        { name: "The Cut", url: "https://www.thecut.com/feed/rss/index.xml" },
        { name: "Refinery29", url: "https://www.refinery29.com/rss.xml" },
        { name: "Highsnobiety", url: "https://www.highsnobiety.com/feed/" },
        { name: "Hypebeast", url: "https://hypebeast.com/feed" },
        { name: "Complex Style", url: "https://www.complex.com/style/rss" },
        { name: "Dazed", url: "https://www.dazeddigital.com/rss" },
        { name: "i-D", url: "https://i-d.vice.com/en_us/rss" },
        { name: "Paper Magazine", url: "https://www.papermag.com/rss.xml" },
        { name: "Nylon", url: "https://www.nylon.com/rss.xml" },
        { name: "Teen Vogue", url: "https://www.teenvogue.com/feed/rss" },
        { name: "InStyle", url: "https://www.instyle.com/feeds/all/ins.rss" },
        { name: "Marie Claire", url: "https://www.marieclaire.com/rss/all.xml/" },
      ],
      ru: [
        { name: "The Blueprint", url: "https://theblueprint.ru/rss" },
        { name: "FashionUnited RU", url: "https://fashionunited.ru/rss" },
        { name: "Wonderzine", url: "https://www.wonderzine.com/rss" },
        { name: "Buro 24/7", url: "https://www.buro247.ru/rss" },
        { name: "Vogue Russia", url: "https://www.vogue.ru/rss" },
        { name: "GQ Russia", url: "https://www.gq.ru/rss" },
        { name: "Elle Russia", url: "https://www.elle.ru/rss" },
        { name: "Harper's Bazaar RU", url: "https://bazaar.ru/rss" },
        { name: "Tatler", url: "https://www.tatler.ru/rss" },
        { name: "Glamour Russia", url: "https://www.glamour.ru/rss" },
        { name: "Cosmopolitan RU", url: "https://www.cosmo.ru/rss" },
        { name: "InStyle Russia", url: "https://instyle.ru/rss" },
        { name: "Marie Claire RU", url: "https://www.marieclaire.ru/rss" },
        { name: "Grazia Russia", url: "https://graziamagazine.ru/rss" },
        { name: "L'Officiel Russia", url: "https://www.lofficielrussia.ru/rss" },
        { name: "РБК Стиль", url: "https://style.rbc.ru/rss" },
        { name: "Афиша Мода", url: "https://daily.afisha.ru/rss/beauty/" },
        { name: "Numero Russia", url: "https://www.numero.ru/rss" },
        { name: "Собака.ru", url: "https://www.sobaka.ru/rss" },
        { name: "The Symbol", url: "https://www.thesymbol.ru/rss" },
      ],
    },
  },
  {
    id: "music",
    icon: Music,
    sources: {
      en: [
        { name: "Billboard", url: "https://www.billboard.com/feed/" },
        { name: "Rolling Stone", url: "https://www.rollingstone.com/feed/" },
        { name: "Pitchfork", url: "https://pitchfork.com/rss/news/" },
        { name: "NME", url: "https://www.nme.com/feed" },
        { name: "Stereogum", url: "https://www.stereogum.com/feed/" },
        { name: "Consequence", url: "https://consequence.net/feed/" },
        { name: "Brooklyn Vegan", url: "https://www.brooklynvegan.com/feed/" },
        { name: "The Line of Best Fit", url: "https://www.thelineofbestfit.com/feed" },
        { name: "DIY Magazine", url: "https://diymag.com/feed" },
        { name: "Clash Magazine", url: "https://www.clashmusic.com/feed" },
        { name: "Paste Magazine", url: "https://www.pastemagazine.com/rss/music" },
        { name: "Spin", url: "https://www.spin.com/feed/" },
        { name: "Complex Music", url: "https://www.complex.com/music/rss" },
        { name: "Hypebeast Music", url: "https://hypebeast.com/music/feed" },
        { name: "EDM.com", url: "https://edm.com/feed" },
        { name: "Dancing Astronaut", url: "https://dancingastronaut.com/feed/" },
        { name: "Your EDM", url: "https://www.youredm.com/feed/" },
        { name: "DJ Mag", url: "https://djmag.com/feed" },
        { name: "Resident Advisor", url: "https://ra.co/xml/news.xml" },
        { name: "r/Music", url: "https://www.reddit.com/r/Music/.rss" },
      ],
      ru: [
        { name: "Rap.ru", url: "https://rap.ru/rss" },
        { name: "The Flow", url: "https://the-flow.ru/feed" },
        { name: "Soundcheck", url: "https://soundcheck.ru/rss" },
        { name: "InterMedia Музыка", url: "https://www.intermedia.ru/rss/music" },
        { name: "Афиша Музыка", url: "https://daily.afisha.ru/rss/music/" },
        { name: "Colta Музыка", url: "https://www.colta.ru/rss/music" },
        { name: "Moskva FM", url: "https://moskva.fm/rss" },
        { name: "RockCult", url: "https://rockcult.ru/feed/" },
        { name: "HeadBanger", url: "https://headbanger.ru/rss" },
        { name: "Darkside.ru", url: "https://www.darkside.ru/rss/" },
        { name: "ProRock", url: "https://prorock.ru/rss" },
        { name: "MusicBox", url: "https://musicbox-tv.ru/rss" },
        { name: "Radio Record", url: "https://www.radiorecord.ru/rss" },
        { name: "Europa Plus", url: "https://europaplus.ru/rss" },
        { name: "Музыка Mail.ru", url: "https://music.mail.ru/rss/" },
        { name: "Zvuki.ru", url: "https://zvuki.ru/rss" },
        { name: "Наше Радио", url: "https://www.nashe.ru/rss" },
        { name: "Русское Радио", url: "https://rusradio.ru/rss" },
        { name: "HipHop4Real", url: "https://hiphop4real.ru/feed/" },
        { name: "InRock", url: "https://inrock.ru/feed/" },
      ],
    },
  },
  {
    id: "interesting",
    icon: Sparkles,
    sources: {
      en: [
        { name: "Mental Floss", url: "https://www.mentalfloss.com/rss" },
        { name: "Atlas Obscura", url: "https://www.atlasobscura.com/feeds/latest" },
        { name: "r/todayilearned", url: "https://www.reddit.com/r/todayilearned/.rss" },
        { name: "r/interestingasfuck", url: "https://www.reddit.com/r/interestingasfuck/.rss" },
        { name: "r/mildlyinteresting", url: "https://www.reddit.com/r/mildlyinteresting/.rss" },
        { name: "r/Damnthatsinteresting", url: "https://www.reddit.com/r/Damnthatsinteresting/.rss" },
        { name: "Bored Panda", url: "https://www.boredpanda.com/feed/" },
        { name: "Oddity Central", url: "https://www.odditycentral.com/feed" },
        { name: "Neatorama", url: "https://www.neatorama.com/feed/" },
        { name: "The Week", url: "https://theweek.com/rss" },
        { name: "Listverse", url: "https://listverse.com/feed/" },
        { name: "How Stuff Works", url: "https://www.howstuffworks.com/feed" },
        { name: "Big Think", url: "https://bigthink.com/feed/" },
        { name: "Nautilus", url: "https://nautil.us/rss/all" },
        { name: "Aeon", url: "https://aeon.co/feed.rss" },
        { name: "Open Culture", url: "https://www.openculture.com/feed" },
        { name: "Brain Pickings", url: "https://www.brainpickings.org/feed/" },
        { name: "Wait But Why", url: "https://waitbutwhy.com/feed" },
        { name: "Cracked", url: "https://www.cracked.com/feed" },
        { name: "IFLScience", url: "https://www.iflscience.com/rss" },
      ],
      ru: [
        { name: "AdMe", url: "https://www.adme.ru/rss/" },
        { name: "Naked Science", url: "https://naked-science.ru/feed" },
        { name: "Пикабу Лучшее", url: "https://pikabu.ru/rss/best" },
        { name: "Fishki Интересное", url: "https://fishki.net/rss" },
        { name: "Популярная механика", url: "https://www.popmech.ru/rss/" },
        { name: "N+1", url: "https://nplus1.ru/rss" },
        { name: "XX2 век", url: "https://22century.ru/feed" },
        { name: "Лайфхакер", url: "https://lifehacker.ru/feed/" },
        { name: "Arzamas", url: "https://arzamas.academy/feed" },
        { name: "Теории и практики", url: "https://theoryandpractice.ru/rss" },
        { name: "T&P Журнал", url: "https://tinkoff.ru/journal/rss/" },
        { name: "Вокруг света", url: "https://www.vokrugsveta.ru/rss/" },
        { name: "National Geographic RU", url: "https://nat-geo.ru/rss" },
        { name: "Discovery Russia", url: "https://www.discoverychannel.ru/rss" },
        { name: "SciOne", url: "https://scione.ru/feed/" },
        { name: "QWERTY", url: "https://qwerty.media/rss" },
        { name: "Knife Media", url: "https://knife.media/feed/" },
        { name: "Batrachospermum", url: "https://batrachospermum.livejournal.com/data/rss" },
        { name: "Антропогенез", url: "https://antropogenez.ru/rss" },
        { name: "Indicador", url: "https://indicator.ru/rss" },
      ],
    },
  },
  {
    id: "facts_research",
    icon: FlaskConical,
    sources: {
      en: [
        { name: "Our World in Data", url: "https://ourworldindata.org/rss.xml" },
        { name: "ScienceDaily", url: "https://www.sciencedaily.com/rss/all.xml" },
        { name: "Nature", url: "https://www.nature.com/subjects/science/rss" },
        { name: "Science Magazine", url: "https://www.science.org/rss/news_current.xml" },
        { name: "Scientific American", url: "https://www.scientificamerican.com/rss/all" },
        { name: "New Scientist", url: "https://www.newscientist.com/feed/home" },
        { name: "Phys.org", url: "https://phys.org/rss-feed/" },
        { name: "Live Science", url: "https://www.livescience.com/feeds/all" },
        { name: "Space.com", url: "https://www.space.com/feeds/all" },
        { name: "Ars Technica Science", url: "https://feeds.arstechnica.com/arstechnica/science" },
        { name: "Wired Science", url: "https://www.wired.com/feed/category/science/latest/rss" },
        { name: "Quanta Magazine", url: "https://www.quantamagazine.org/feed/" },
        { name: "PLOS ONE", url: "https://journals.plos.org/plosone/feed/atom" },
        { name: "MIT Tech Review", url: "https://www.technologyreview.com/feed/" },
        { name: "The Conversation", url: "https://theconversation.com/us/articles.atom" },
        { name: "Smithsonian", url: "https://www.smithsonianmag.com/rss/science-nature/" },
        { name: "Popular Science", url: "https://www.popsci.com/feed/" },
        { name: "Discover Magazine", url: "https://www.discovermagazine.com/rss" },
        { name: "r/science", url: "https://www.reddit.com/r/science/.rss" },
        { name: "r/askscience", url: "https://www.reddit.com/r/askscience/.rss" },
      ],
      ru: [
        { name: "Элементы", url: "https://elementy.ru/rss" },
        { name: "Naked Science", url: "https://naked-science.ru/feed" },
        { name: "ПостНаука", url: "https://postnauka.ru/feed" },
        { name: "N+1", url: "https://nplus1.ru/rss" },
        { name: "Indicator.ru", url: "https://indicator.ru/rss" },
        { name: "ТАСС Наука", url: "https://nauka.tass.ru/rss" },
        { name: "Газета.ру Наука", url: "https://www.gazeta.ru/science/rss.xml" },
        { name: "Лента Наука", url: "https://lenta.ru/rss/news/science" },
        { name: "РИА Наука", url: "https://ria.ru/science/index.xml" },
        { name: "Хабр Наука", url: "https://habr.com/ru/rss/hub/popular_science/" },
        { name: "Популярная механика", url: "https://www.popmech.ru/rss/" },
        { name: "XX2 век", url: "https://22century.ru/feed" },
        { name: "ScienceFirst", url: "https://sciencefirst.ru/feed/" },
        { name: "Чердак", url: "https://chrdk.ru/feed" },
        { name: "InScience", url: "https://inscience.news/feed/" },
        { name: "Наука и жизнь", url: "https://www.nkj.ru/rss/" },
        { name: "Биомолекула", url: "https://biomolecula.ru/feed" },
        { name: "Антропогенез", url: "https://antropogenez.ru/rss" },
        { name: "SciOne", url: "https://scione.ru/feed/" },
        { name: "Sci-Hub News", url: "https://sci-hub.ru/rss" },
      ],
    },
  },
  {
    id: "movies",
    icon: Film,
    sources: {
      en: [
        { name: "Variety", url: "https://variety.com/feed/" },
        { name: "Hollywood Reporter", url: "https://www.hollywoodreporter.com/feed/" },
        { name: "Collider", url: "https://collider.com/feed/" },
        { name: "Screen Rant", url: "https://screenrant.com/feed/" },
        { name: "IndieWire", url: "https://www.indiewire.com/feed/" },
        { name: "Deadline", url: "https://deadline.com/feed/" },
        { name: "Slash Film", url: "https://www.slashfilm.com/feed/" },
        { name: "JoBlo", url: "https://www.joblo.com/feed/" },
        { name: "Den of Geek Movies", url: "https://www.denofgeek.com/movies/feed/" },
        { name: "Empire", url: "https://www.empireonline.com/rss" },
        { name: "Total Film", url: "https://www.gamesradar.com/totalfilm/rss/" },
        { name: "The Playlist", url: "https://theplaylist.net/feed/" },
        { name: "Film School Rejects", url: "https://filmschoolrejects.com/feed/" },
        { name: "Cinemablend", url: "https://www.cinemablend.com/rss/topic/movies/all" },
        { name: "ComingSoon", url: "https://www.comingsoon.net/feed" },
        { name: "Dark Horizons", url: "https://www.darkhorizons.com/feed/" },
        { name: "The Wrap", url: "https://www.thewrap.com/feed/" },
        { name: "Roger Ebert", url: "https://www.rogerebert.com/feed" },
        { name: "r/movies", url: "https://www.reddit.com/r/movies/.rss" },
        { name: "r/boxoffice", url: "https://www.reddit.com/r/boxoffice/.rss" },
      ],
      ru: [
        { name: "КиноПоиск", url: "https://www.kinopoisk.ru/rss/news.xml" },
        { name: "Film.ru", url: "https://www.film.ru/rss" },
        { name: "InterMedia", url: "https://www.intermedia.ru/rss" },
        { name: "Кинокадр", url: "https://www.kinokadr.ru/rss" },
        { name: "Filmz.ru", url: "https://www.filmz.ru/rss" },
        { name: "Кино Mail.ru", url: "https://kino.mail.ru/rss/" },
        { name: "Афиша Кино", url: "https://daily.afisha.ru/rss/cinema/" },
        { name: "DTF Кино", url: "https://dtf.ru/rss/cinema" },
        { name: "Cinemaholics", url: "https://cinemaholics.ru/feed/" },
        { name: "КГ-Портал", url: "https://www.kg-portal.ru/rss" },
        { name: "Кинопоиск HD", url: "https://hd.kinopoisk.ru/rss" },
        { name: "Okko Журнал", url: "https://okko.tv/journal/rss" },
        { name: "IVI Журнал", url: "https://www.ivi.ru/journal/rss" },
        { name: "Сеанс", url: "https://seance.ru/feed/" },
        { name: "Film.ru Рецензии", url: "https://www.film.ru/rss/reviews" },
        { name: "Миры Кино", url: "https://world-of-kino.ru/feed/" },
        { name: "Кинотеатр", url: "https://www.kinoteatr.ru/rss" },
        { name: "FilmPro", url: "https://www.filmpro.ru/rss" },
        { name: "Кинобизнес", url: "https://kinobusiness.com/rss" },
        { name: "Kinometro", url: "https://www.kinometro.ru/rss" },
      ],
    },
  },
  {
    id: "series",
    icon: Tv,
    sources: {
      en: [
        { name: "TVLine", url: "https://tvline.com/feed/" },
        { name: "Deadline TV", url: "https://deadline.com/v/tv/feed/" },
        { name: "Den of Geek TV", url: "https://www.denofgeek.com/tv/feed/" },
        { name: "TV Guide", url: "https://www.tvguide.com/feed/" },
        { name: "TV Fanatic", url: "https://www.tvfanatic.com/feed/" },
        { name: "Entertainment Weekly TV", url: "https://ew.com/tv/feed/" },
        { name: "Digital Spy TV", url: "https://www.digitalspy.com/tv/feed/" },
        { name: "Vulture TV", url: "https://www.vulture.com/tv/rss/index.xml" },
        { name: "The AV Club TV", url: "https://www.avclub.com/tv-reviews/rss" },
        { name: "TV Insider", url: "https://www.tvinsider.com/feed/" },
        { name: "IGN TV", url: "https://www.ign.com/tv/feed.xml" },
        { name: "What's on Netflix", url: "https://www.whats-on-netflix.com/feed/" },
        { name: "Decider", url: "https://decider.com/feed/" },
        { name: "r/television", url: "https://www.reddit.com/r/television/.rss" },
        { name: "r/netflix", url: "https://www.reddit.com/r/netflix/.rss" },
        { name: "r/HouseOfTheDragon", url: "https://www.reddit.com/r/HouseOfTheDragon/.rss" },
        { name: "Screen Rant TV", url: "https://screenrant.com/tv-shows/feed/" },
        { name: "Collider TV", url: "https://collider.com/tv/feed/" },
        { name: "Showbiz Cheat Sheet", url: "https://www.cheatsheet.com/feed/" },
        { name: "TV Tropes", url: "https://tvtropes.org/pmwiki/rss.php" },
      ],
      ru: [
        { name: "Serialu.net", url: "https://serialu.net/rss" },
        { name: "Film.ru Сериалы", url: "https://www.film.ru/rss/series" },
        { name: "LostFilm", url: "https://www.lostfilm.tv/rss.xml" },
        { name: "NewStudio", url: "https://newstudio.tv/rss" },
        { name: "Кинопоиск Сериалы", url: "https://www.kinopoisk.ru/rss/series.xml" },
        { name: "DTF Сериалы", url: "https://dtf.ru/rss/series" },
        { name: "Афиша Сериалы", url: "https://daily.afisha.ru/rss/series/" },
        { name: "SeasonVar", url: "https://seasonvar.ru/rss.xml" },
        { name: "Кино Mail Сериалы", url: "https://kino.mail.ru/rss/series/" },
        { name: "IVI Сериалы", url: "https://www.ivi.ru/series/rss" },
        { name: "Okko Сериалы", url: "https://okko.tv/series/rss" },
        { name: "Wink Сериалы", url: "https://wink.ru/series/rss" },
        { name: "Кинопоиск HD Сериалы", url: "https://hd.kinopoisk.ru/series/rss" },
        { name: "Premier Сериалы", url: "https://premier.one/series/rss" },
        { name: "Start Сериалы", url: "https://start.ru/series/rss" },
        { name: "КГ-Портал Сериалы", url: "https://www.kg-portal.ru/rss/series" },
        { name: "Сериаломания", url: "https://serialomania.ru/rss" },
        { name: "MyShows", url: "https://myshows.me/rss" },
        { name: "TV Трекер", url: "https://rutracker.org/forum/rss.php?f=189" },
        { name: "Сериалист", url: "https://serialist.ru/rss" },
      ],
    },
  },
  {
    id: "russia_news",
    icon: Flag,
    ruOnly: true,
    sources: {
      en: [],
      ru: [
        { name: "РИА Новости", url: "https://ria.ru/export/rss2/archive/index.xml" },
        { name: "Лента.ру", url: "https://lenta.ru/rss" },
        { name: "Коммерсант", url: "https://www.kommersant.ru/RSS/news.xml" },
        { name: "Ведомости", url: "https://www.vedomosti.ru/rss/news" },
        { name: "Известия", url: "https://iz.ru/xml/rss/all.xml" },
        { name: "Газета.ру", url: "https://www.gazeta.ru/export/rss/lenta.xml" },
        { name: "ТАСС Россия", url: "https://tass.ru/rss/v2.xml?sections=politics" },
        { name: "Интерфакс", url: "https://www.interfax.ru/rss.asp" },
        { name: "RT на русском", url: "https://russian.rt.com/rss" },
        { name: "РБК", url: "https://rssexport.rbc.ru/rbcnews/news/30/full.rss" },
        { name: "Московский комсомолец", url: "https://www.mk.ru/rss/index.xml" },
        { name: "Российская газета", url: "https://rg.ru/xml/index.xml" },
        { name: "Комсомольская правда", url: "https://www.kp.ru/rss/allsections.xml" },
        { name: "Аргументы и факты", url: "https://aif.ru/rss/all.php" },
        { name: "Правда.ру", url: "https://www.pravda.ru/rss/" },
        { name: "Новые известия", url: "https://newizv.ru/rss" },
        { name: "Свободная пресса", url: "https://svpressa.ru/rss/" },
        { name: "Regnum", url: "https://regnum.ru/rss/news" },
        { name: "ИА REGNUM", url: "https://regnum.ru/rss" },
        { name: "Царьград", url: "https://tsargrad.tv/rss" },
      ],
    },
  },
  {
    id: "medicine",
    icon: Stethoscope,
    sources: {
      en: [
        { name: "Medical News Today", url: "https://www.medicalnewstoday.com/rss" },
        { name: "ScienceDaily Health", url: "https://www.sciencedaily.com/rss/health_medicine.xml" },
        { name: "NIH News", url: "https://www.nih.gov/news-events/news-releases/rss.xml" },
        { name: "WebMD", url: "https://rssfeeds.webmd.com/rss/rss.aspx?RSSSource=RSS_PUBLIC" },
        { name: "Mayo Clinic", url: "https://newsnetwork.mayoclinic.org/feed/" },
        { name: "Cleveland Clinic", url: "https://health.clevelandclinic.org/feed/" },
        { name: "Harvard Health", url: "https://www.health.harvard.edu/blog/feed" },
        { name: "STAT News", url: "https://www.statnews.com/feed/" },
        { name: "Healthline", url: "https://www.healthline.com/rss" },
        { name: "Everyday Health", url: "https://www.everydayhealth.com/rss/" },
        { name: "The Lancet", url: "https://www.thelancet.com/rssfeed/lancet_online.xml" },
        { name: "BMJ", url: "https://www.bmj.com/rss/recent.xml" },
        { name: "JAMA", url: "https://jamanetwork.com/rss/site_3/67.xml" },
        { name: "New England Journal", url: "https://www.nejm.org/action/showFeed?type=etoc&feed=rss" },
        { name: "r/medicine", url: "https://www.reddit.com/r/medicine/.rss" },
        { name: "r/health", url: "https://www.reddit.com/r/Health/.rss" },
        { name: "MedPage Today", url: "https://www.medpagetoday.com/rss/headlines.xml" },
        { name: "Medscape", url: "https://www.medscape.com/rss/news.xml" },
        { name: "Reuters Health", url: "https://www.reuters.com/news/rss/healthNews" },
        { name: "CNN Health", url: "https://rss.cnn.com/rss/cnn_health.rss" },
      ],
      ru: [
        { name: "Medportal", url: "https://medportal.ru/rss" },
        { name: "Доктор Питер", url: "https://doctorpiter.ru/rss" },
        { name: "Медвестник", url: "https://medvestnik.ru/rss" },
        { name: "Vademecum", url: "https://vademec.ru/rss" },
        { name: "Здоровье Mail.ru", url: "https://health.mail.ru/rss/" },
        { name: "Медуза Здоровье", url: "https://meduza.io/rss/health" },
        { name: "РБК Здоровье", url: "https://style.rbc.ru/health/rss" },
        { name: "ТАСС Здоровье", url: "https://tass.ru/rss/v2.xml?sections=obschestvo" },
        { name: "Газета.ру Здоровье", url: "https://www.gazeta.ru/science/rss.xml" },
        { name: "Лента Здоровье", url: "https://lenta.ru/rss/news/health" },
        { name: "НаПоправку", url: "https://napopravku.ru/rss" },
        { name: "ПроБолезни", url: "https://probolezny.ru/rss" },
        { name: "Медицинская газета", url: "https://www.mgzt.ru/rss" },
        { name: "Фармацевтический вестник", url: "https://pharmvestnik.ru/rss" },
        { name: "Remedium", url: "https://www.remedium.ru/rss" },
        { name: "Медновости", url: "https://mednovosti.by/rss" },
        { name: "Здравком", url: "https://zdravkom.ru/rss" },
        { name: "Здоровье инфо", url: "https://zdorovieinfo.ru/rss" },
        { name: "Med-info", url: "https://med-info.ru/rss" },
        { name: "ЗОЖ инфо", url: "https://zozhnik.ru/feed/" },
      ],
    },
  },
  {
    id: "youtube_trends",
    icon: Youtube,
    sources: {
      en: [
        { name: "YouTube Trending US (RSSHub)", url: "https://rsshub.app/youtube/trending/US" },
        { name: "YouTube Trending UK (RSSHub)", url: "https://rsshub.app/youtube/trending/GB" },
        { name: "r/youtube", url: "https://www.reddit.com/r/youtube/.rss" },
        { name: "r/youtubers", url: "https://www.reddit.com/r/youtubers/.rss" },
        { name: "r/NewTubers", url: "https://www.reddit.com/r/NewTubers/.rss" },
        { name: "r/videos Top", url: "https://www.reddit.com/r/videos/top/.rss?t=day" },
        { name: "r/InternetIsBeautiful", url: "https://www.reddit.com/r/InternetIsBeautiful/.rss" },
        { name: "Tubefilter", url: "https://www.tubefilter.com/feed/" },
        { name: "Creator Insider", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCBcRF18a7Qf58cCRy5xuWwQ" },
        { name: "YouTube Creators", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCkRfArvrzheW2E7b6SVT7vQ" },
        { name: "MrBeast", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCX6OQ3DkcsbYNE6H8uQQuVA" },
        { name: "PewDiePie", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC-lHJZR3Gqxm24_Vd_AJ5Yw" },
        { name: "Dude Perfect", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCRijo3ddMTht_IHyNSNXpNQ" },
        { name: "Veritasium", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCHnyfMqiRRG1u-2MsSQLbXA" },
        { name: "Marques Brownlee", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCBJycsmduvYEL83R_U4JriQ" },
        { name: "Dexerto", url: "https://www.dexerto.com/feed/" },
        { name: "DotEsports", url: "https://dotesports.com/feed" },
        { name: "The Verge Creators", url: "https://www.theverge.com/creators/rss/index.xml" },
        { name: "Mashable Social", url: "https://mashable.com/feeds/rss/social-media" },
        { name: "Later Blog", url: "https://later.com/blog/feed/" },
      ],
      ru: [
        { name: "YouTube Trending RU (RSSHub)", url: "https://rsshub.app/youtube/trending/RU" },
        { name: "r/Pikabu", url: "https://www.reddit.com/r/Pikabu/.rss" },
        { name: "DTF", url: "https://dtf.ru/rss" },
        { name: "VC.ru", url: "https://vc.ru/rss" },
        { name: "Хабр Медиа", url: "https://habr.com/ru/rss/flows/develop/" },
        { name: "Пикабу Горячее", url: "https://pikabu.ru/rss/hot" },
        { name: "BadComedian", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC6cqazSR6CnVMClY0bJI0Lg" },
        { name: "Wylsacom", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCMCgOm8GZkHp8zJ6l7_hIuA" },
        { name: "Дудь", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCMCgOm8GZkHp8zJ6l7_hIuA&name=dud" },
        { name: "Редакция", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC1eFXmJNkjITxPFWTy6RsWg" },
        { name: "Чикен Карри", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCzVBHZFV0H6c_MeLdU7e4Kg" },
        { name: "Utopia Show", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCVse72Lxn4jL3s9bvA8oKWw" },
        { name: "Макс Максимов", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCb6RY3IUbJSkmT6JYMdlyhg" },
        { name: "Room Factory", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCFNzRBWN0LmEHCwQFZ2gMDw" },
        { name: "Антон Птушкин", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCN0P_gDz3VYs61MXgJvKo8w" },
        { name: "varlamov", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC101o-vQ2iOj9vr00JUlyKw" },
        { name: "Mediasat", url: "https://mediasat.info/rss" },
        { name: "Cossa", url: "https://www.cossa.ru/rss/" },
        { name: "Sostav", url: "https://www.sostav.ru/rss/" },
        { name: "AdIndex", url: "https://adindex.ru/rss/" },
      ],
    },
  },
  {
    id: "pets",
    icon: PawPrint,
    sources: {
      en: [
        { name: "PetMD", url: "https://www.petmd.com/rss" },
        { name: "The Spruce Pets", url: "https://www.thesprucepets.com/rss" },
        { name: "American Kennel Club", url: "https://www.akc.org/feed/" },
        { name: "Dogster", url: "https://www.dogster.com/feed" },
        { name: "Catster", url: "https://www.catster.com/feed" },
        { name: "Pet Age", url: "https://www.petage.com/feed/" },
        { name: "Pet Business", url: "https://www.petbusiness.com/feed/" },
        { name: "Groomer to Groomer", url: "https://www.groomertogroomer.com/feed/" },
        { name: "Modern Dog Magazine", url: "https://moderndogmagazine.com/feed" },
        { name: "Daily Paws", url: "https://www.dailypaws.com/feed" },
        { name: "r/dogs", url: "https://www.reddit.com/r/dogs/.rss" },
        { name: "r/cats", url: "https://www.reddit.com/r/cats/.rss" },
        { name: "r/aww", url: "https://www.reddit.com/r/aww/.rss" },
        { name: "r/pets", url: "https://www.reddit.com/r/Pets/.rss" },
        { name: "r/doggrooming", url: "https://www.reddit.com/r/doggrooming/.rss" },
        { name: "Rover Blog", url: "https://www.rover.com/blog/feed/" },
        { name: "BarkPost", url: "https://barkpost.com/feed/" },
        { name: "The Dodo", url: "https://www.thedodo.com/rss" },
        { name: "Vetstreet", url: "https://www.vetstreet.com/rss" },
        { name: "Fear Free Pets", url: "https://fearfreepets.com/feed/" },
        { name: "Dog Fashion", url: "https://www.dogfashionblog.com/feed/" },
        { name: "Posh Puppy Boutique", url: "https://www.poshpuppyboutique.com/blog/feed/" },
        { name: "Zooplus Magazine", url: "https://www.zooplus.co.uk/magazine/feed" },
        { name: "Pet Industry News", url: "https://petindustrynews.com/feed/" },
        { name: "Whole Dog Journal", url: "https://www.whole-dog-journal.com/feed/" },
      ],
      ru: [
        { name: "Petstory", url: "https://petstory.ru/rss" },
        { name: "Питомцы Mail.ru", url: "https://pets.mail.ru/rss/" },
        { name: "Petshop.ru", url: "https://www.petshop.ru/rss/" },
        { name: "Dogsy", url: "https://dogsy.ru/feed/" },
        { name: "ПроКошек", url: "https://prokoshku.ru/feed/" },
        { name: "Котофей", url: "https://kotofey.ru/feed/" },
        { name: "Dog-Care", url: "https://dog-care.ru/feed/" },
        { name: "Cat-Expert", url: "https://cat-expert.ru/feed/" },
        { name: "ZooAtlas", url: "https://zooatlas.ru/rss" },
        { name: "VetInfo", url: "https://vetinfo.ru/feed/" },
        { name: "Грумер Pro", url: "https://groomerpro.ru/feed/" },
        { name: "Питомник.ру", url: "https://pitomnik.ru/rss" },
        { name: "Собака.ру", url: "https://sobaka.ru/feed/" },
        { name: "Кот и Пёс", url: "https://kotopes.ru/feed/" },
        { name: "ZooMir", url: "https://zoomir.ru/rss" },
        { name: "Любимчик", url: "https://lubimchik.ru/feed/" },
        { name: "Zoo Club", url: "https://zooclub.ru/rss" },
        { name: "Мир кошек", url: "https://mirkoshki.ru/feed/" },
        { name: "Мир собак", url: "https://mirsobak.net/feed/" },
        { name: "Pet Сити", url: "https://petcity.ru/rss" },
        { name: "Ветеринар онлайн", url: "https://vetmag.ru/feed/" },
        { name: "Домашние животные", url: "https://domashnie-zhivotnye.ru/feed/" },
        { name: "Зверополис", url: "https://zveropolis.ru/feed/" },
        { name: "Grooming Russia", url: "https://grooming-russia.ru/feed/" },
        { name: "Pet Fashion RU", url: "https://petfashion.ru/feed/" },
      ],
    },
  },
];

export const defaultCategory: CategoryId = "world_news";

export function getCategoryPreset(id: CategoryId): CategoryPreset | undefined {
  return categoryPresets.find(p => p.id === id);
}

export function getAvailableCategories(language: "ru" | "en"): CategoryPreset[] {
  return categoryPresets.filter(p => {
    if (p.ruOnly && language !== "ru") return false;
    return true;
  });
}
